spring.application.name=InterviewChatbot

spring.datasource.url = jdbc:postgresql://localhost:5432/Interview_Chatbot
spring.datasource.username = postgres
spring.datasource.password = 1234

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true


#Queries

user.query.Login = Select * from users where email = ?;
user.query.SignUp = Insert INTO users(name, email, password, role) values (?,?,?,?)